---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.exemplo.com
  resources:
  - configmapwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.exemplo.com
  resources:
  - configmapwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.exemplo.com
  resources:
  - configmapwatchers/status
  verbs:
  - get
  - patch
  - update
