apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: default
data:
  config.json: |
    {
      "database": {
        "host": "localhost",
        "port": 5432
      },
      "api": {
        "endpoint": "https://api.example.com"
      }
    }
  environment: "production" 